permalink:           pretty

# Setup
title:               Malicious Website, Online
tagline:             'probably a thing?'
description:         'definitely a thing'
url:                 http://cgds.github.io
baseurl:             ''
plugins:             [jekyll-paginate]
paginate:            5


# About/contact
author:
  name:              Connor
  url:               https://twitter.com/
  email:             connor.savage@gmail.com

# Custom vars
version:             1.0.0
